# Generated by Django 4.1 on 2022-08-22 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 26, 51, 752850, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
